### ISSUE TITLE
Is Brain Workshop 5 compatible with macOS Catalina?

### ISSUE THREAD

**Issue by lgtout** [samcv/brainworkshop#14]
Hi,
The macOS Catalina updater says Brain Workshop 4.8.4 will no longer launch after the update.  Do you know if this will also be an issue with Brain Workshop 5?
Thanks!
Julian

**Comment by xantares** [comment]
probably fixed by #13 too

**Comment by xantares** [comment]
@lgtout, can you close this one ?

**Comment by lgtout** [comment]
@xantares I was delaying upgrading to Catalina until I knew I could continue to use Brain Workshop on it.  So I still haven't verified that it works on Catalina.  Has anyone else done so?

**Comment by xantares** [comment]
v4.8.4 was broken a while ago by the different pyglet updates, no wonder it's reported as broken, now the fixes are in it should work

**Comment by lgtout** [comment]
@xantares Ok.  I'll upgrade to Catalina and see what happens.

**Comment by xantares** [comment]
I'm closing this one, as there's nothing to fix.
