### ISSUE TITLE
Pressing "C" to change game type does nothing

### ISSUE THREAD

**Issue by lgtout** [samcv/brainworkshop#15]
Pressing "C" to change game type does nothing.  I should mention that I'm using changes in @xantares' pull request #13  because the app was crashing on start.  I'm on macOS Sierra.

**Comment by xantares** [comment]
yes, I got this one too

**Comment by lgtout** [comment]
I've verified that @xantares pull request #13 fixes this issue.  Thank you so much, @xantares!

**Comment by xantares** [comment]
you mean PR #16 ?

**Comment by lgtout** [comment]
Oops!  Yes, @xantares: #16.
