### ISSUE TITLE
Fullscreen in Jaeggi Mode not centered

### ISSUE THREAD

**Issue by mark-olenik** [samcv/brainworkshop#2]
The cross in Jaeggi Mode fullscreen is sometimes in the center, sometimes the grid is on the left half of the screen. Only option is `JAEGGI_MODE=True`. Can replicate it in KDE Plasma and LXDE, running Arch.

![1](https://user-images.githubusercontent.com/6062680/34334764-5d1f507e-e95a-11e7-8832-78213ec0eb34.png)
![2](https://user-images.githubusercontent.com/6062680/34334765-5d41a390-e95a-11e7-861a-ccdd4606ba12.png)

**Comment by samcv** [comment]
This is an issue. As far as I remember is this was a side effect of making elements zoom properly to the screen. I'm sure this could be fixed with more tweaking. Also, which Python version are you using?

**Comment by mark-olenik** [comment]
I'm using `Python 3.6.6`. I tried finding the culprit in the code but to me it seemed this was an issue with `pyglet` itself. Where in the code do you think is the problem, maybe in `MyWindow`?

**Comment by samcv** [comment]
You mean the cross `+` mark when the game is going? The screenshots you posted originally only show the title screen? Can you show me some screenshots of the grid?

**Comment by mark-olenik** [comment]
The bug affects everything, the cross is also shifted just as the title screen. The screenshots below are from a screen with a higher resolution than before, and the cross in the second is barely visible but it's also in the top left corner.

![s1](https://user-images.githubusercontent.com/6062680/42511656-683d2d9c-844a-11e8-9d46-a201e1f89361.png)

![s2](https://user-images.githubusercontent.com/6062680/42511657-685ca60e-844a-11e8-88aa-7c2bcbf9e36a.png)

**Comment by samcv** [comment]
@mark-olenik can you check the latest commit in master? I think the issue is fixed.

**Comment by mark-olenik** [comment]
@samcv Indeed, problem solved. Thank you!

**Comment by samcv** [comment]
Awesome. Closing the issue.
