### ISSUE TITLE
pyglet 1.5.0 breaks the game on Fedora 31

### ISSUE THREAD

**Issue by stefankober** [samcv/brainworkshop#20]
On Fedora 31 installing pyglet via `pip install` will install pyglet 1.5.0.
This will cause the sound to only happen on every second tick, among other confusions.

The workaround is simple: `pip install pyglet==1.4.0 --user` - this will also install `future`, `libfuturize`, `past` and `libpasteurize` in `$HOME/.local/lib/$PYTHONVERSION/site-packages`. You can just copy all the folders from there to the game folder and everything works like a charm.

For now I had no time to debug this deeper. If this is an issue for more people I might be inclined to do it.

**Comment by mnowotnik** [comment]
Actually pyglet 1.4.0 is broken in Python 3.7.6, so I advise to install 1.4.10.

**Comment by xantares** [comment]
seems this is caused by this commit
https://github.com/pyglet/pyglet/commit/3ac72826d31b5f1d132cf7c143bb196bf86f4353
but there are commits related to audio queued following in that 1.5 branch
any advice @benmoran56 ?

**Comment by xantares** [comment]
they just released 1.5.1 and the bug is gone, so I guess this was just a pyglet bug

**Comment by benmoran56** [comment]
Thanks for updating, and I'm glad that fixed it for you.
