### ISSUE TITLE
Sound in Every Other Trial Rather Than Every Trial - Arch Linux x86_64

### ISSUE THREAD

**Issue by Alchemek** [samcv/brainworkshop#22]
I'm using Arch Linux x86_64. So I installed the latest git version of
Brain Workshop 5 beta just a little while ago (like an hour ago), and it seems to work
much better than Brain Workshop 4.8.4. But there's something
mysterious that actually breaks the game entirely: I hear sound in
every other trial rather than every trial. I can't imagine why. It
looks like everything installed properly. I installed this package
using the Arch Linux AUR brainworkshop-git package.

Any suggestions? Any further information I can provide?

**Comment by xantares** [comment]
yes, that's the pyglet 1.5.0 bug (see #20), just upgrade pyglet using pip until they upgrade
