### ISSUE TITLE
Playtime in the last 24 hours only updates after restart

### ISSUE THREAD

**Issue by marki-o** [samcv/brainworkshop#25]
As the title says, the playtime that is shown in the top right corner doesn't automatically update after a session, only after a restart of the program.

Is that a bug or supposed to be that way?

Version 5.0-beta

**Comment by xantares** [comment]
I guess its a bug. It's a great first issue if you want to contribute :)

**Comment by molenik** [comment]
OK, I'll give it a try!

**Comment by xantares** [comment]
@markolenik I had to revert your commit because it was causing https://github.com/samcv/brainworkshop/issues/27

parse_statsfile calls retrieve_progress which in turns calls enforce_standard_mode which resets the sessions parameters (nback, trials, speed etc), so its hard to untangle things here
