### ISSUE TITLE
App spoils the solution

### ISSUE THREAD

**Issue by Umsturz** [samcv/brainworkshop#29]
Whenever I miss the correct position or letter sound the text on the bottom: "Left-click..." or "Right-click..." turns blue right at the end of the 3 seconds, see attached picture. I have been using the app for a week now and I think that this bug only appeared yesterday. This behavior is very distracting, even though I would like an immediate feedback I don't want to spoil the missed positions. A workaround is to hide the text, but then there is no immediate feedback anymore.
<img width="901" alt="brainworkshop" src="https://user-images.githubusercontent.com/6431242/89433160-4560b300-d742-11ea-83ec-6816acc8544b.png">

**Comment by xantares** [comment]
This is not a bug: the app is supposed to behave that way:
- when you miss a match the text turns blue briefly at the end of the trial
- when you wrongly flag a match the text turns blue until the end of the trial

**Comment by Umsturz** [comment]
Oh. This is a surprise. Thank you for clearing that up.

**Comment by lgtout** [comment]
> This is not a bug: the app is supposed to behave that way:
> 
> * when you miss a match the text turns blue briefly at the end of the trial
> * when you wrongly flag a match the text turns blue until the end of the trial

@xantares Should this behavior also occur when the user is in Manual Mode?  I have `SHOW_FEEDBACK = True` in `brainworkshop.pyw`, but it seems to have no effect.

**Comment by lgtout** [comment]
Never mind!  The color change was so subtle that I only noticed it when I stopped trying to play the game at the same time.  Is there a way to make the effect _more_ prominent?

**Comment by xantares** [comment]
@lgtout I guess you can tryto fiddle with the colors (~rgb format):
https://github.com/samcv/brainworkshop/blob/master/brainworkshop.pyw#L561
