### ISSUE TITLE
Where is config.ini?

### ISSUE THREAD

**Issue by lgtout** [samcv/brainworkshop#30]
Is configuration still controlled via a `config.ini` in the `data` folder`?  I've tried changing the configuration by putting a `config.ini` in `data` and in the root folder.  And I've tried modifying settings in `brainworkshop.pyw`.  But, strangely, this seems to have no effect.  

I can't find the stats file either.  According to `Readme-stats.txt`, it should be in the `data` folder as well.

Thanks!

**Comment by lgtout** [comment]
Nm.  I found it at `~/Library/Application Support/Brain Workshop/data/config.ini` on Mac.

**Comment by nunmap** [comment]
`~/.brainworkshop/data/config.ini` on UNIX
