### ISSUE TITLE
App crashes when it is supposed to play sound

### ISSUE THREAD

**Issue by srbiotik** [samcv/brainworkshop#4]
I am using Ubuntu 18.04, with python three, all the libraries installed, AvBin and also future, past, libfuturize.
On the first trial, when it is supposed to play a letter sound it suddenly crashes.
I tried to debug it and i get:
![image](https://user-images.githubusercontent.com/19361217/42402821-6f1b0938-817d-11e8-8a7e-bf6247de9176.png)

**Comment by samcv** [comment]
@srbiotik what is the exact python version? Can you try and temporarily move your ~/.brainworkshop folder just in case you have made any preference changes? Does it still crash with the folder moved? If it doesn't crash anymore can I see your configuration file ~/.brainworkshop/config.ini?

**Comment by srbiotik** [comment]
[raa@raa-P55-UD3L ~]$ python3 --version
Python 3.6.5

It seems to have stopped crashing when i renamed the folder, perhaps there was a ~/.brainworkshop folder created from a previous installation?
Nevertheless, you can find the old configuration in the attachment. it will be *.txt extension since GitHub doesn't support *.ini files.
[config.txt](https://github.com/samcv/brainworkshop/files/2216122/config.txt)

**Comment by xantares** [comment]
try updating pyglet
