### ISSUE TITLE
AVBin trouble on Windows

### ISSUE THREAD

**Issue by bwuser2018** [samcv/brainworkshop#8]
The program starts without AVBin succsessfully (and says: "AVBin not detected. Music disabled.")
But with AVBin installed in the system it crashes (It shows a window filled with white, eats CPU and memory)

![bw_fail](https://user-images.githubusercontent.com/43085478/45252441-bb4e1b00-b36f-11e8-91b3-151278064c03.png)

**IDLE output:**
Unexpected error loading library avbin: [WinError 193] %1 is not a valid Win32 application
Warning: Could not load AVbin. Music disabled.

This is usually due to Windows Data Execution Prevention (DEP). Due to a bug in
AVbin, a library used for decoding sound files, music is not available when DEP is enabled. To enable music, disable DEP for Brain Workshop. To simply get rid of this message, set USE_MUSIC = False in your config.ini file.

To disable DEP:

1. Open Control Panel -> System
2. Select Advanced System Settings
3. Click on Performance -> Settings
4. Click on the Data Execution Prevention tab
5. Either select the "Turn on DEP for essential Windows programs and services only" option, or add an exception for Brain Workshop.

Press any key to continue without music support.

Traceback (most recent call last):
  File "C:\Users\User\Desktop\bw_new\brainworkshop.pyw", line 4760, in <module>
    Message(msg)
  File "C:\Users\User\Desktop\bw_new\brainworkshop.pyw", line 662, in __init__
    font_name=self.fontlist_serif,
AttributeError: 'Message' object has no attribute 'fontlist_serif'

"Turn on DEP for essential Windows programs and services only" option already set.

**Comment by xantares** [comment]
update pyglet, they dropped avbin now
