### ISSUE TITLE
Will not start in Linux Mint 18.x based Ubuntu 16.04?

### ISSUE THREAD

**Issue by phd21** [samcv/brainworkshop#9]
Hi Samcv,

Thanks for forking this into version 5 for Python 2 and 3 and updating it. 

Unfortunately, I cannot get this to work in my Linux Mint 18.x based Ubuntu 16.04. 

Some people in the Linux Mint forum would like to use "Brainworkshop" and could not get it to work, then I found your fork "Brainworkshop 5", and I cannot get it to load. I have installed all the dependencies I think. Does this still use the "avbin" like the older one because I installed that too?

These are the results from my console terminal using either python or python3.

`python brainworkshop.pyw
Warning: Could not load AVbin. Music disabled.

This is usually due to Windows Data Execution Prevention (DEP). Due to a bug in
AVbin, a library used for decoding sound files, music is not available when DEP is enabled. To enable music, disable DEP for Brain Workshop. To simply get rid of this message, set USE_MUSIC = False in your config.ini file.

To disable DEP:

1. Open Control Panel -> System
2. Select Advanced System Settings
3. Click on Performance -> Settings
4. Click on the Data Execution Prevention tab
5. Either select the "Turn on DEP for essential Windows programs and services only" option, or add an exception for Brain Workshop.

Press any key to continue without music support.

Exception AttributeError: "'FFmpegSource' object has no attribute '_packet'" in <bound method FFmpegSource.__del__ of <pyglet.media.codecs.ffmpeg.FFmpegSource object at 0x7fc7c3d63110>> ignored
Traceback (most recent call last):
  File "brainworkshop.pyw", line 4735, in <module>
    brain_icon.set_position(field.center_x - brain_icon.width//2,
AttributeError: 'Sprite' object has no attribute 'set_position'
`

Best regards,
Phil (phd21)
phd21mint@gmail.com

**Comment by xantares** [comment]
that's a change in pyglet, try #13

**Comment by lgtout** [comment]
I had the same error on Mac Sierra.  Using @xantares' changes fixed it.

**Comment by xantares** [comment]
@samcv this is fixed in #13
